# Storage Backend
storage.backend=cql
storage.hostname=127.0.0.1

# Optional: Specify Cassandra keyspace
storage.cassandra.keyspace=janusgraph
storage.cassandra.compression=true
storage.cassandra.compression-class=lz4

# default properties
schema.default=none

#caching
cache.db-cache=true
cache.db-cache-size = 0.5
cache.db-cache-clean-wait = 20

## Indexing Backend
index.search.backend=elasticsearch
index.search.hostname=127.0.0.1
index.search.elasticsearch.interface=REST_CLIENT
index.search.elasticsearch.bulk-refresh=false